'''
 Created on Wed Jan 01 2020

 Copyright (c) 2020 yuchonghuang@sina.cn
'''

STOCK_RECORD_STOCK_ID = '股票代码'
STOCK_RECORD_STOCK_NAME = '股票名称'
STOCK_RECORD_STOCK_NAME_1 = '股票简称'
STOCK_RECORD_STOCK_DATE = '日期'

STOCK_RECORD_OPEN_PRICE = '开盘价'
STOCK_RECORD_CLOSE_PRICE_TODAY = '收盘价'
STOCK_RECORD_CLOSE_PRICE_YESTERDAY = '昨日收盘价'
STOCK_RECORD_HIGHEST_PRICE = '最高价'
STOCK_RECORD_LOWEST_PRICE = '最低价'
STOCK_RECORD_VOLUME = '成交量(股)'
STOCK_RECORD_TURNOVER = '成交额(元)'
STOCK_RECORD_VOLUME_RATIO = '量比'
STOCK_RECORD_QUOTE_CHANGE = '涨跌幅(%)'

STOCK_RECORD_5MA = '5日均线'
STOCK_RECORD_10MA = '10日均线'
STOCK_RECORD_20MA = '20日均线'
STOCK_RECORD_30MA = '30日均线'
STOCK_RECORD_60MA = '60日均线'
STOCK_RECORD_120MA = '120日均线'
STOCK_RECORD_240MA = '240日均线'

STOCK_RECORD_5MA_1 = '5MA'
STOCK_RECORD_10MA_1 = '10MA'
STOCK_RECORD_20MA_1 = '20MA'
STOCK_RECORD_30MA_1 = '30MA'
STOCK_RECORD_60MA_1 = '60MA'
STOCK_RECORD_120MA_1= '120MA'
STOCK_RECORD_240MA_1 = '240MA'

STOCK_RECORD_MACD = 'MACD'
STOCK_RECORD_BOLL_UPPER = 'BOLL上轨'
STOCK_RECORD_BOLL_MID = 'BOLL中轨'
STOCK_RECORD_BOLL_LOWER = 'BOLL下轨'

STOCK_RECORD_RSI6 = 'RSI6'
STOCK_RECORD_RSI12 = 'RSI12'
STOCK_RECORD_RSI24 = 'RSI24'

STOCK_RECORD_RSI6_1 = 'rsi6值'
STOCK_RECORD_RSI12_1 = 'rsi12值'
STOCK_RECORD_RSI24_1 = 'rsi24值'

STOCK_RECORD_KDJ_K = 'K'
STOCK_RECORD_KDJ_D = 'D'
STOCK_RECORD_KDJ_J = 'J'

STOCK_RECORD_CIRCULATION_MARKET_VALUE = '流通市值'
STOCK_RECORD_CIRCULATION_MARKET_VALUE_1 = 'a股流通市值'
STOCK_RECORD_INDUSTRY = '行业'
STOCK_RECORD_INDUSTRY_1 = '所属行业'
STOCK_RECORD_CONCEPT = '概念'
STOCK_RECORD_CONCEPT_1 = '所属概念'
STOCK_RECORD_DAY_TO_MARKET = '上市天数'
STOCK_RECORD_TECHNICAL_FORM = '技术形态'

STOCK_RECORD_BOLL_PERCENTAGE= 'BOLL百分比'
STOCK_RECORD_BOLL_WIDTH = 'BOLL带宽'
STOCK_RECORD_DISTANCE_TO_BOLL_UPPER = '到BOLL上轨'
STOCK_RECORD_DISTANCE_TO_BOLL_MID = '到BOLL中轨'
STOCK_RECORD_DISTANCE_TO_BOLL_LOWER = '到BOLL下轨'
STOCK_RECORD_DISTANCE_BETWEEN_UPPER_LOWER = 'BOLL上下轨百分比'
STOCK_RECORD_GUAILI_SHORT = '短线均线乖离度'
STOCK_RECORD_GUAILI_MID = '中线均线乖离度'
STOCK_RECORD_GUAILI_LONG = '长线均线乖离度'

STOCK_RECORD_DISTANCE_TO_MA5 = '股价距离5日线距离'
STOCK_RECORD_DISTANCE_TO_MA10 = '股价距离10日线距离'
STOCK_RECORD_DISTANCE_TO_MA20 = '股价距离月线距离'
STOCK_RECORD_DISTANCE_TO_MA30 = '股价距离30日线距离'
STOCK_RECORD_DISTANCE_TO_MA60 = '股价距离季线距离'
STOCK_RECORD_DISTANCE_TO_MA120 = '股价距离半年线距离'
STOCK_RECORD_DISTANCE_TO_MA240 = '股价距离年线距离'

ALL_STOCK_RECORDS_SHORT_KEYS = (
    STOCK_RECORD_OPEN_PRICE,
    STOCK_RECORD_CLOSE_PRICE_TODAY,
    STOCK_RECORD_CLOSE_PRICE_YESTERDAY,
    STOCK_RECORD_HIGHEST_PRICE,
    STOCK_RECORD_LOWEST_PRICE,
    STOCK_RECORD_VOLUME,
    STOCK_RECORD_TURNOVER,
    STOCK_RECORD_VOLUME_RATIO,
    STOCK_RECORD_QUOTE_CHANGE,

    STOCK_RECORD_5MA,
    STOCK_RECORD_10MA,
    STOCK_RECORD_20MA,
    STOCK_RECORD_30MA,
    STOCK_RECORD_60MA,
    STOCK_RECORD_120MA,
    STOCK_RECORD_240MA,
)

ALL_STOCK_RECORDS_KEYS = (
    STOCK_RECORD_STOCK_ID,
    STOCK_RECORD_STOCK_NAME,
    STOCK_RECORD_STOCK_DATE,

    STOCK_RECORD_OPEN_PRICE,
    STOCK_RECORD_CLOSE_PRICE_TODAY,
    STOCK_RECORD_CLOSE_PRICE_YESTERDAY,
    STOCK_RECORD_HIGHEST_PRICE,
    STOCK_RECORD_LOWEST_PRICE,
    STOCK_RECORD_VOLUME,
    STOCK_RECORD_TURNOVER,
    STOCK_RECORD_VOLUME_RATIO,
    STOCK_RECORD_QUOTE_CHANGE,

    STOCK_RECORD_5MA,
    STOCK_RECORD_10MA,
    STOCK_RECORD_20MA,
    STOCK_RECORD_30MA,
    STOCK_RECORD_60MA,
    STOCK_RECORD_120MA,
    STOCK_RECORD_240MA,

    STOCK_RECORD_MACD,
    STOCK_RECORD_BOLL_UPPER,
    STOCK_RECORD_BOLL_MID,
    STOCK_RECORD_BOLL_LOWER,

    STOCK_RECORD_RSI6,
    STOCK_RECORD_RSI12,
    STOCK_RECORD_RSI24,

    STOCK_RECORD_KDJ_K,
    STOCK_RECORD_KDJ_D,
    STOCK_RECORD_KDJ_J,

    STOCK_RECORD_CIRCULATION_MARKET_VALUE,
    STOCK_RECORD_INDUSTRY,
    STOCK_RECORD_CONCEPT,
    STOCK_RECORD_DAY_TO_MARKET,
    STOCK_RECORD_TECHNICAL_FORM,

    STOCK_RECORD_BOLL_PERCENTAGE,
    STOCK_RECORD_BOLL_WIDTH,
    STOCK_RECORD_DISTANCE_TO_BOLL_UPPER,
    STOCK_RECORD_DISTANCE_TO_BOLL_MID,
    STOCK_RECORD_DISTANCE_TO_BOLL_LOWER,
    STOCK_RECORD_DISTANCE_BETWEEN_UPPER_LOWER,
    STOCK_RECORD_GUAILI_SHORT,
    STOCK_RECORD_GUAILI_MID,
    STOCK_RECORD_GUAILI_LONG,

    STOCK_RECORD_DISTANCE_TO_MA5,
    STOCK_RECORD_DISTANCE_TO_MA10 ,
    STOCK_RECORD_DISTANCE_TO_MA20,
    STOCK_RECORD_DISTANCE_TO_MA30 ,
    STOCK_RECORD_DISTANCE_TO_MA60,
    STOCK_RECORD_DISTANCE_TO_MA120 ,
    STOCK_RECORD_DISTANCE_TO_MA240 ,
)

STOCK_UNIFY_MAP = {
    STOCK_RECORD_STOCK_NAME_1: STOCK_RECORD_STOCK_NAME,
    STOCK_RECORD_5MA_1:STOCK_RECORD_5MA,
    STOCK_RECORD_10MA_1:STOCK_RECORD_10MA,
    STOCK_RECORD_20MA_1:STOCK_RECORD_20MA,
    STOCK_RECORD_30MA_1:STOCK_RECORD_30MA,
    STOCK_RECORD_60MA_1:STOCK_RECORD_60MA,
    STOCK_RECORD_120MA_1:STOCK_RECORD_120MA,
    STOCK_RECORD_240MA_1:STOCK_RECORD_240MA,
    STOCK_RECORD_RSI6_1:STOCK_RECORD_RSI6,
    STOCK_RECORD_RSI12_1:STOCK_RECORD_RSI12,
    STOCK_RECORD_RSI24_1:STOCK_RECORD_RSI24,
    STOCK_RECORD_CIRCULATION_MARKET_VALUE_1:STOCK_RECORD_CIRCULATION_MARKET_VALUE,
    STOCK_RECORD_INDUSTRY_1:STOCK_RECORD_INDUSTRY,
    STOCK_RECORD_CONCEPT_1:STOCK_RECORD_CONCEPT,
}

STOCK_RECORD_MAP = {
    STOCK_RECORD_STOCK_ID: 'DM',
    STOCK_RECORD_STOCK_NAME: 'MC',
    STOCK_RECORD_STOCK_DATE: 'RQ',

    STOCK_RECORD_OPEN_PRICE: 'KPJ',
    STOCK_RECORD_CLOSE_PRICE_TODAY: 'SPJ',
    STOCK_RECORD_CLOSE_PRICE_YESTERDAY: 'ZRSPJ',
    STOCK_RECORD_HIGHEST_PRICE: 'ZGJ',
    STOCK_RECORD_LOWEST_PRICE: 'ZDJ',
    STOCK_RECORD_VOLUME: 'CJL',
    STOCK_RECORD_TURNOVER: 'CJE',
    STOCK_RECORD_VOLUME_RATIO: 'LB',
    STOCK_RECORD_QUOTE_CHANGE: 'ZDF',

    STOCK_RECORD_5MA: 'ma5',
    STOCK_RECORD_10MA: 'ma10',
    STOCK_RECORD_20MA: 'ma20',
    STOCK_RECORD_30MA: 'ma30',
    STOCK_RECORD_60MA: 'ma60',
    STOCK_RECORD_120MA: 'ma120',
    STOCK_RECORD_240MA: 'ma240',

    STOCK_RECORD_MACD: 'macd',
    STOCK_RECORD_BOLL_UPPER: 'bollup',
    STOCK_RECORD_BOLL_MID: 'bollmid',
    STOCK_RECORD_BOLL_LOWER: 'bolllo',

    STOCK_RECORD_RSI6: 'rsi6',
    STOCK_RECORD_RSI12: 'rsi12',
    STOCK_RECORD_RSI24: 'rsi24',

    STOCK_RECORD_KDJ_K: 'K',
    STOCK_RECORD_KDJ_D: 'D',
    STOCK_RECORD_KDJ_J: 'J',

    STOCK_RECORD_CIRCULATION_MARKET_VALUE: 'LTSZ',
    STOCK_RECORD_INDUSTRY: 'HY',
    STOCK_RECORD_CONCEPT: 'GN',
    STOCK_RECORD_DAY_TO_MARKET: 'SSRQ',
    STOCK_RECORD_TECHNICAL_FORM: 'JSXT',
    STOCK_RECORD_BOLL_PERCENTAGE:'BOLL_BFB',
    STOCK_RECORD_BOLL_WIDTH:'BOLL_DK',
    STOCK_RECORD_DISTANCE_TO_BOLL_UPPER:'D_BOLL_S',
    STOCK_RECORD_DISTANCE_TO_BOLL_MID:'D_BOLL_Z',
    STOCK_RECORD_DISTANCE_TO_BOLL_LOWER:'D_BOLL_X',
    STOCK_RECORD_DISTANCE_BETWEEN_UPPER_LOWER:'X_BOLL_S',
    STOCK_RECORD_GUAILI_SHORT:'DGL',
    STOCK_RECORD_GUAILI_MID:'ZGL',
    STOCK_RECORD_GUAILI_LONG:'CGL',

    STOCK_RECORD_DISTANCE_TO_MA5:'DMA5',
    STOCK_RECORD_DISTANCE_TO_MA10:'DMA10',
    STOCK_RECORD_DISTANCE_TO_MA20:'DMA20',
    STOCK_RECORD_DISTANCE_TO_MA30:'DMA30',
    STOCK_RECORD_DISTANCE_TO_MA60:'DMA60',
    STOCK_RECORD_DISTANCE_TO_MA120 :'DMA120',
    STOCK_RECORD_DISTANCE_TO_MA240:'DMA240',
}

def LongNameToShort(key):
    if key in STOCK_UNIFY_MAP:
        key = STOCK_UNIFY_MAP[key]

    if key in STOCK_RECORD_MAP:
        return STOCK_RECORD_MAP[key]
    
    return key

def ShortNameToLong(value):
    res = [k for k, v in STOCK_RECORD_MAP.items() if v == value]
    if res is None or len(res) == 0:
        return value
    else:
        return res[0]

def ValidateStockMap():
    for key in ALL_STOCK_RECORDS_KEYS:
        if key not in STOCK_RECORD_MAP:
            raise Exception('%s, not in the keys' % (key))

    for key in STOCK_RECORD_MAP.keys():
        if key not in ALL_STOCK_RECORDS_KEYS:
            raise Exception('%s, not in the keys' % (key))

    size1 = len(ALL_STOCK_RECORDS_KEYS)
    size2 = len(STOCK_RECORD_MAP)
    if size1 != size2:
        raise Exception('duplicate keys! %s != %s' % (size1, size2))

    values = list(STOCK_RECORD_MAP.values())
    res = []
    for v in values:
        if v not in res:
            res.append(v)
        else:
            msg = "ValidateStockMap failed!, '%s' alrady in list" % (v)
            raise Exception(msg)

    print('ValidateStockMap, everything is ok!')

if __name__ == '__main__':
    ValidateStockMap()
    print(LongNameToShort(STOCK_RECORD_STOCK_ID))
    print(LongNameToShort("ddd"))
    print(ShortNameToLong('id'))
    print(ShortNameToLong('ddd'))
